apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: mysqls.lemonmysql.io
spec:
  group: lemonmysql.io
  names:
    kind: Mysql
    listKind: MysqlList
    plural: mysqls
    singular: mysql
  scope: Namespaced
  version: v1alpha1
  subresources:
    status: {}
